/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Regiones */
        get: operations["list_regiones_api_v1_regiones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comunas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comunas */
        get: operations["list_comunas_api_v1_comunas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/establecimientos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Establecimientos */
        get: operations["list_establecimientos_api_v1_establecimientos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/establecimientos/{rbd}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ficha */
        get: operations["get_ficha_api_v1_establecimientos__rbd__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sedes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sedes */
        get: operations["list_sedes_api_v1_sedes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cursos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cursos */
        get: operations["list_cursos_api_v1_cursos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cursos/resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumen Cursos */
        get: operations["resumen_cursos_api_v1_cursos_resumen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indicadores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Indicadores */
        get: operations["list_indicadores_api_v1_indicadores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actividades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Actividades */
        get: operations["list_actividades_api_v1_actividades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imagenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Imagenes */
        get: operations["list_imagenes_api_v1_imagenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_api_v1_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActividadOut */
        ActividadOut: {
            /** Id */
            id: number;
            /** Rbd */
            rbd: number;
            /** Nombre */
            nombre: string;
            /** Tipo */
            tipo?: string | null;
            /** Nivel */
            nivel?: string | null;
            /** Exigencia */
            exigencia?: string | null;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Establecimientos */
            establecimientos: components["schemas"]["EstablecimientoListItem"][];
            /** Indicadores */
            indicadores: {
                [key: string]: components["schemas"]["IndicadorOut"][];
            };
            /** Cursos Resumen */
            cursos_resumen: {
                [key: string]: components["schemas"]["CursoResumenOut"][];
            };
            /** Sedes */
            sedes: {
                [key: string]: components["schemas"]["SedeOut"][];
            };
        };
        /** ComunaOut */
        ComunaOut: {
            /** Codigo */
            codigo: number;
            /** Nombre */
            nombre: string;
            /** Codigo Region */
            codigo_region: number;
        };
        /** CursoOut */
        CursoOut: {
            /** Rbd */
            rbd: number;
            /** Codigo Curso */
            codigo_curso: number;
            /** Codigo Sede */
            codigo_sede: number;
            /** Glosa Grupo Ensenanza */
            glosa_grupo_ensenanza?: string | null;
            /** Glosa Ensenanza */
            glosa_ensenanza?: string | null;
            /** Glosa Nivel */
            glosa_nivel?: string | null;
            /** Etiqueta Nivel */
            etiqueta_nivel?: string | null;
            /** Sexo */
            sexo?: string | null;
            /** Glosa Jornada */
            glosa_jornada?: string | null;
            /** Glosa Especialidad */
            glosa_especialidad?: string | null;
            /** Glosa Grupo Pago */
            glosa_grupo_pago?: string | null;
            /** Codigo Ensenanza */
            codigo_ensenanza?: number | null;
            /** Codigo Nivel */
            codigo_nivel?: number | null;
            /** Codigo Jornada */
            codigo_jornada?: number | null;
            /** Codigo Sexo */
            codigo_sexo?: number | null;
            /** Codigo Especialidad */
            codigo_especialidad?: number | null;
            /** Unico Comuna */
            unico_comuna?: boolean | null;
            /** Proporcion Excelencia Transicion */
            proporcion_excelencia_transicion?: number | null;
            /** Proporcion Excelencia Regimen */
            proporcion_excelencia_regimen?: number | null;
            /** Proporcion Especializacion Temprana */
            proporcion_especializacion_temprana?: number | null;
            /** Copago Cuotas */
            copago_cuotas?: number | null;
            /** Copago Valor */
            copago_valor?: number | null;
            /** Cupos Totales */
            cupos_totales?: number | null;
            /** Vacantes Rango Inferior */
            vacantes_rango_inferior?: number | null;
            /** Vacantes Rango Superior */
            vacantes_rango_superior?: number | null;
            /** Porcentaje Cambio Inferior */
            porcentaje_cambio_inferior?: number | null;
            /** Porcentaje Cambio Superior */
            porcentaje_cambio_superior?: number | null;
            /** Repitentes Anio Actual */
            repitentes_anio_actual?: number | null;
            /** Repitentes Nivel Anterior */
            repitentes_nivel_anterior?: number | null;
            /** Pre Inscritos Anio Siguiente */
            pre_inscritos_anio_siguiente?: number | null;
            /** Cambios Inferior */
            cambios_inferior?: number | null;
            /** Cambios Superior */
            cambios_superior?: number | null;
            /** Pre Vacantes Inferior */
            pre_vacantes_inferior?: number | null;
            /** Pre Vacantes Superior */
            pre_vacantes_superior?: number | null;
            /** Rango */
            rango?: number | null;
            /** Postulantes Anio Anterior */
            postulantes_anio_anterior?: number | null;
            /** Movimiento Lista Espera Anterior */
            movimiento_lista_espera_anterior?: number | null;
        };
        /** CursoResumenOut */
        CursoResumenOut: {
            /** Codigo Curso */
            codigo_curso: number;
            /** Glosa Nivel */
            glosa_nivel?: string | null;
            /** Etiqueta Nivel */
            etiqueta_nivel?: string | null;
            /** Sexo */
            sexo?: string | null;
            /** Glosa Jornada */
            glosa_jornada?: string | null;
            /** Copago Cuotas */
            copago_cuotas?: number | null;
            /** Copago Valor */
            copago_valor?: number | null;
            /** Cupos Totales */
            cupos_totales?: number | null;
        };
        /** EstablecimientoListItem */
        EstablecimientoListItem: {
            /** Rbd */
            rbd: number;
            /** Nombre */
            nombre: string;
            /** Dependencia */
            dependencia: string;
            /** Regimen */
            regimen?: string | null;
            /** Nivel Minimo */
            nivel_minimo?: string | null;
            /** Nivel Maximo */
            nivel_maximo?: string | null;
            /**
             * Etiquetas
             * @default []
             */
            etiquetas: string[];
            /** Alumnos Matriculados */
            alumnos_matriculados?: number | null;
            /** Comuna */
            comuna?: string | null;
            /** Region */
            region?: string | null;
        };
        /** EstablecimientoListResponse */
        EstablecimientoListResponse: {
            /** Results */
            results: components["schemas"]["EstablecimientoListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** EstablecimientoOut */
        EstablecimientoOut: {
            /** Rbd */
            rbd: number;
            /** Nombre */
            nombre: string;
            /** Dependencia */
            dependencia: string;
            /** Telefono */
            telefono?: string | null;
            /** Mail */
            mail?: string | null;
            /** Url */
            url?: string | null;
            /**
             * Habilitado Postular
             * @default true
             */
            habilitado_postular: boolean;
            /**
             * Publicado
             * @default false
             */
            publicado: boolean;
            /** Nivel Minimo */
            nivel_minimo?: string | null;
            /** Nivel Maximo */
            nivel_maximo?: string | null;
            /** Director */
            director?: string | null;
            /**
             * Etiquetas
             * @default []
             */
            etiquetas: string[];
            /** Resumen Proyecto */
            resumen_proyecto?: string | null;
            /** Documento Proyecto */
            documento_proyecto?: string | null;
            /** Documento Reglamento */
            documento_reglamento?: string | null;
            /**
             * Internado
             * @default false
             */
            internado: boolean;
            /**
             * Integracion
             * @default false
             */
            integracion: boolean;
            /**
             * Subvencion Preferencial
             * @default false
             */
            subvencion_preferencial: boolean;
            /**
             * Peib
             * @default false
             */
            peib: boolean;
            /** Politica Uniforme */
            politica_uniforme?: string | null;
            /** Orientacion Religiosa */
            orientacion_religiosa?: string | null;
            /** Alumnos Matriculados */
            alumnos_matriculados?: number | null;
            /** Promedio Alumnos Por Curso */
            promedio_alumnos_por_curso?: number | null;
            /** Cantidad Docentes */
            cantidad_docentes?: number | null;
            /** Regimen */
            regimen?: string | null;
        };
        /** FichaOut */
        FichaOut: {
            establecimiento: components["schemas"]["EstablecimientoOut"];
            /** Sedes */
            sedes: components["schemas"]["SedeOut"][];
            /** Cursos Resumen */
            cursos_resumen: components["schemas"]["CursoResumenOut"][];
            /** Indicadores */
            indicadores: components["schemas"]["IndicadorOut"][];
            /** Actividades */
            actividades: components["schemas"]["ActividadOut"][];
            /** Imagenes */
            imagenes: components["schemas"]["ImagenOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Dataset Version */
            dataset_version: string;
        };
        /** ImagenOut */
        ImagenOut: {
            /** Id */
            id: number;
            /** Rbd */
            rbd: number;
            /** Nombre */
            nombre?: string | null;
            /** Url */
            url?: string | null;
            /**
             * Principal
             * @default false
             */
            principal: boolean;
        };
        /** IndicadorOut */
        IndicadorOut: {
            /** Id */
            id: number;
            /** Rbd */
            rbd: number;
            /** Tipo Indicador */
            tipo_indicador: string;
            /** Nombre Indicador */
            nombre_indicador: string;
            /** Titulo Indicador */
            titulo_indicador?: string | null;
            /** Nivel Indicador */
            nivel_indicador?: string | null;
            /** Descripcion Indicador */
            descripcion_indicador?: string | null;
            /** Puntaje */
            puntaje?: number | null;
            /** Comparacion Gse Numero */
            comparacion_gse_numero?: number | null;
            /** Comparacion Gse Glosa */
            comparacion_gse_glosa?: string | null;
        };
        /** RegionOut */
        RegionOut: {
            /** Codigo */
            codigo: number;
            /** Nombre */
            nombre: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["EstablecimientoListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** SedeOut */
        SedeOut: {
            /** Rbd */
            rbd: number;
            /** Codigo Sede */
            codigo_sede: number;
            /** Codigo Region */
            codigo_region: number;
            /** Codigo Comuna */
            codigo_comuna: number;
            /** Region */
            region: string;
            /** Comuna */
            comuna: string;
            /** Calle */
            calle?: string | null;
            /** Latitud */
            latitud?: number | null;
            /** Longitud */
            longitud?: number | null;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Establecimientos */
            establecimientos: number;
            /** Sedes */
            sedes: number;
            /** Cursos */
            cursos: number;
            /** Comunas */
            comunas: number;
            /** Regiones */
            regiones: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    stats_api_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    list_regiones_api_v1_regiones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionOut"][];
                };
            };
        };
    };
    list_comunas_api_v1_comunas_get: {
        parameters: {
            query: {
                /** @description Código de región (filtro en cascada) */
                region: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunaOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query?: {
                q?: string | null;
                comuna?: string | null;
                region?: number | null;
                dependencia?: string | null;
                regimen?: string | null;
                nivel?: string | null;
                copago_max?: number | null;
                etiquetas?: string[] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_establecimientos_api_v1_establecimientos_get: {
        parameters: {
            query?: {
                dependencia?: string | null;
                regimen?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstablecimientoListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ficha_api_v1_establecimientos__rbd__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rbd: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FichaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sedes_api_v1_sedes_get: {
        parameters: {
            query: {
                rbd: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SedeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cursos_api_v1_cursos_get: {
        parameters: {
            query: {
                rbd: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resumen_cursos_api_v1_cursos_resumen_get: {
        parameters: {
            query: {
                rbd: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursoResumenOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_indicadores_api_v1_indicadores_get: {
        parameters: {
            query: {
                rbd: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicadorOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_actividades_api_v1_actividades_get: {
        parameters: {
            query: {
                rbd: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActividadOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_imagenes_api_v1_imagenes_get: {
        parameters: {
            query: {
                rbd: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagenOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_compare_get: {
        parameters: {
            query: {
                /** @description RBDs separados por coma (máx. 10) */
                rbds: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
